"""Drop chunks table

Revision ID: 45324e97bccf
Revises: b1a3f7e20c41
Create Date: 2026-06-11 07:33:41.798769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45324e97bccf'
down_revision: Union[str, None] = 'b1a3f7e20c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_book_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_library_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_shelf_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_user_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('library_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shelf_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('chunks_book_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('chunks_library_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], name=op.f('chunks_shelf_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chunks_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chunks_pkey'))
    )
    op.create_index(op.f('ix_chunks_user_id'), 'chunks', ['user_id'], unique=False)
    op.create_index(op.f('ix_chunks_shelf_id'), 'chunks', ['shelf_id'], unique=False)
    op.create_index(op.f('ix_chunks_library_id'), 'chunks', ['library_id'], unique=False)
    op.create_index(op.f('ix_chunks_book_id'), 'chunks', ['book_id'], unique=False)
    op.create_index(op.f('ix_chunks_book_id'), 'chunks', ['book_id'], unique=False)
    # ### end Alembic commands ###
